### ISSUE TITLE
As a Vendor Admin , I would like to be able to edit  different items in the catalog

### ISSUE THREAD

**Issue by realfahadrahman** [Aly-Hussein/SOEN-341-project#1]
Initiator: Vendor of products.

As a vendor, I want to be able to add items to the shop using specific categories to class the items so that the clients have an easier time finding the items wanted.

Story Points:

- [x]  Vendor should be able to add products to catalog.
- [x]  Vendor should be able to add detailed information to the products.
- [x]  Vendor should be able to class items by type in catalog.
- [ ]  Vendor should be able to view and edit only their product's content.

**Comment by MKMicheal** [comment]
The items can be added but are not able to edit yet.

**Comment by MKMicheal** [comment]
Cannot edit yet because of bugs
