### ISSUE TITLE
As a user , i want to be able to login or  and register to  BudjetAmazon 

### ISSUE THREAD

**Issue by yvich** [Aly-Hussein/SOEN-341-project#12]
- [x] login
- [x] registration
- [x] authenfication 
- [x] authorization

**Comment by MKMicheal** [comment]
The login and register functions are working but they are not linked to functionalities yet.

**Comment by MKMicheal** [comment]
Login and register are implemented but do not save to the database because of errors

**Comment by yvich** [comment]
Every of those functionalities have been implemented and they works following recent commits
